include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    # avoid_positional_boolean_parameters: false
    # always_declare_return_types: false
    # type_annotate_public_apis: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    #Freezed README says to ignore these errors
    invalid_annotation_target: ignore
    cancel_subscriptions: ignore
    avoid_positional_boolean_parameters: ignore
    constant_identifier_names: ignore
