name: Test

on:
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'bin/**'
      - 'pubspec.yaml'
      - 'analysis_options.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'bin/**'
      - 'pubspec.yaml'
      - 'analysis_options.yaml'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run analyzer
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4

      - uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test

  coverage:
    name: Code Coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Code Coverage
        run: flutter test --coverage --coverage-path lcov.info
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          slug: EliaTolin/remote_caching